### ISSUE TITLE
Also pass additional parameters from hash?

### ISSUE THREAD

**Issue by roytam1** [jaden/totp-generator#10]
besides KEY like `https://totp.danhersam.com/#/KEY`, I wonder if we can pass additional parameters from hash, like `https://totp.danhersam.com/#/KEY/digits=6/period=60/algorithm=SHA256`?

**Comment by jaden** [comment]
You can already do this: https://github.com/jaden/totp-generator#additional-parameters

**Comment by roytam1** [comment]
> You can already do this: https://github.com/jaden/totp-generator#additional-parameters

pass as query string will also send them to server.
but string after hash will not.

**Comment by rdebath** [comment]
You can pass just the key as the `#` string and the others in the query; that should be fine.

https://totp.danhersam.com/?digits=8&period=30&algorithm=SHA1#/aaaaaaaaaaaaaaah
vs
https://totp.danhersam.com/#/aaaaaaaaaaaaaaah

**Comment by roytam1** [comment]
> https://totp.danhersam.com/?digits=8&period=30&algorithm=SHA1#/aaaaaaaaaaaaaaah

ah, OK I haven't ever think about in this style.
Thanks for your hint.
