### ISSUE TITLE
Add  pages

### ISSUE THREAD

**Issue by DYSON57** [jaden/totp-generator#2]
For simply save link in favs , likes this https://totp.danhersam.com/JBSWY3DPEHPK3PXP code aumatically pasted

**Comment by jaden** [comment]
Good idea, done

https://totp.danhersam.com/#/JBSWY3DPEHPK3PXP

**Comment by DYSON57** [comment]
> 
> 
> Good idea, done
> 
> https://totp.danhersam.com/#/JBSWY3DPEHPK3PXP

If possible add this feature to main page

**Comment by jaden** [comment]
It already is: https://github.com/jaden/totp-generator#private-key-in-url
