### ISSUE TITLE
Generating with custom secret not working

### ISSUE THREAD

**Issue by softmarshmallow** [jaden/totp-generator#6]
1. input new custom secret.
2. wait 30 seconds
3. nothing changes.

**Comment by jaden** [comment]
This can happen if the secret key isn't a valid base32 value. Could you double check?

The token will be updated almost immediately when you add a valid secret key.

https://stackoverflow.com/questions/53600848/how-to-check-if-a-string-is-base32-encoded-in-javascript

**Comment by softmarshmallow** [comment]
Oh. wan't expecting answer this quick. 
I just made a real simple client for this. - https://github.com/bridgedxyz/tiny-mini-micro/blob/main/tiniminimicro/pages/totp.tsx

20 minutes to late LOL T.T

Question: Why does it force us to use base32?

I'm only aware with otplib's totp, and it accepts any kind of secret. (AFAIK)

**Comment by jaden** [comment]
I thought base32 was the standard, but I guess not. The library this tool uses requires the use of a base32 key. Glad you found a solution. 👍
