### ISSUE TITLE
Support the specification of the 'algorithm' parameter

### ISSUE THREAD

**Issue by Muntaner** [jaden/totp-generator#9]
Currently, the 'algorithm' parameter setting is hardcoded to SHA1: https://github.com/jaden/totp-generator/blob/master/public/js/app.js#L58

It could be very useful to have this passed via an input through the UI, similarly to the secret parameter. For example, this URL is a valid TOTP initiator:

`[TOTP_BASE_URL]?algorithm=SHA256&digits=6&issuer=Company&period=30&secret=6M2F7ACSQA898A7842H4EJAODWK53SD
`

But it could not be passed to the totp-generator app, since the SHA256 is unsupported.

**Comment by jaden** [comment]
Thanks for the suggestion, this is now implemented.
